import {randomInt} from "../random_util";

/**
 * Returns a uniformly random integer from the interval [2, 9] + [11, 12].
 * The times table up to 12 is assumed to be known by heart.
 * 0, 1, and 10 are removed because they are too easy to multiply.
 * These numbers are considered the simplest possible to multiply without being trivial.
 */
export function randomSimpleFactor() {
  let result = 2 + randomInt(10);  // [2, 11]
  if (result >= 10) {
    result += 1;
  }
  return result;
}

/**
 * Returns a uniformly random integer from the interval [2, 9] + [11, 99].
 * 0, 1, and 10 are removed because they are too easy to multiply.
 */
export function randomTwoDigitFactor() {
  let result = 2 + randomInt(98);  // [2, 99]
  if (result >= 10) {
    result += 1;
  }
  return result;
}

/**
 * Returns a two digit integer that is greater than 12 and does not have a 0 digit.
 * These numbers are considered sligtly harder to multiply than the ones generated by
 * "generateSimpleFactor".
 */
export function randomNonTrivialTwoDigitFactor() {
  let result = randomInt(100 - 13 - 9);
  result += 13;
  for (let i = 20; i <= 90; i += 10) {
    if (result >= i) {
      result += 1;
    }
  }
  return result;
}
